# Generated by Django 5.0 on 2023-12-05 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(default='', max_length=10, null=True)),
                ('rating', models.CharField(choices=[('G', 'Rate G'), ('PG', 'Rate Pg'), ('PG-13', 'Rate Pg 13'), ('R', 'Rate R'), ('NC-17', 'Rate Nc 17')], default='G', max_length=20)),
                ('synopsis', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
