# Generated by Django 5.0 on 2023-12-06 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_duration_alter_movie_synopsis'),
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
